//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandCategory
    {
        public LandCategory()
        {
            this.LandPlots = new HashSet<LandPlot>();
        }
    
        public int ID { get; set; }
        public string Наименование_участка { get; set; }
        public string Тип { get; set; }
    
        public virtual ICollection<LandPlot> LandPlots { get; set; }
    }
}
