//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandPlot
    {
        public LandPlot()
        {
            this.LeaseAgreements = new HashSet<LeaseAgreement>();
        }
    
        public int ID { get; set; }
        public int RegionID { get; set; }
        public int LandCategoriesID { get; set; }
        public string Кадастровый_номер { get; set; }
        public string Разрешенное_использование { get; set; }
        public Nullable<decimal> Площадь__кв_м_ { get; set; }
        public string Адрес { get; set; }
        public int StatusID { get; set; }
        public System.DateTime Дата_постановки_на_учет { get; set; }
    
        public virtual LandCategory LandCategory { get; set; }
        public virtual PlotStatus PlotStatus { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<LeaseAgreement> LeaseAgreements { get; set; }
    }
}
