//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaseAgreement
    {
        public int ID { get; set; }
        public int LandPlotsID { get; set; }
        public string Название_компании { get; set; }
        public string Арендатор { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_конца { get; set; }
        public int StatusID { get; set; }
    
        public virtual LandPlot LandPlot { get; set; }
        public virtual PlotStatus PlotStatus { get; set; }
    }
}
