//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {

        private static Entities1 _context;

        
        public Entities1()
            : base("name=Entities1")
        {
        }

        public static Entities1 GetContext()
        {
            if (_context == null)
                _context = new Entities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<LandCategory> LandCategories { get; set; }
        public DbSet<LandPlot> LandPlots { get; set; }
        public DbSet<LeaseAgreement> LeaseAgreements { get; set; }
        public DbSet<PlotStatus> PlotStatuses { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
