//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlotStatus
    {
        public PlotStatus()
        {
            this.LandPlots = new HashSet<LandPlot>();
            this.LeaseAgreements = new HashSet<LeaseAgreement>();
        }
    
        public int ID { get; set; }
        public string Статус { get; set; }
    
        public virtual ICollection<LandPlot> LandPlots { get; set; }
        public virtual ICollection<LeaseAgreement> LeaseAgreements { get; set; }
    }
}
