//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.LandPlots = new HashSet<LandPlot>();
        }
    
        public int ID { get; set; }
        public string Название_района { get; set; }
        public decimal Площадь_района__кв_км_ { get; set; }
        public int Численность { get; set; }
    
        public virtual ICollection<LandPlot> LandPlots { get; set; }
    }
}
