//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Min_BID
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public Nullable<int> RolesID { get; set; }
        public string Логин { get; set; }
        public string Хэш_пароль { get; set; }
        public string Соль { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
